### ISSUE TITLE
jdc crash

### ISSUE THREAD

**Issue by lidaobing** [jdcloud-api/jdcloud-cli#26]
$ jdc
Traceback (most recent call last):
  File "/usr/local/bin/jdc", line 7, in <module>
    from jdcloud_cli.jdc import main
  File "/usr/local/lib/python3.7/site-packages/jdcloud_cli/jdc.py", line 21, in <module>
    from jdcloud_cli.controllers.configure_controller import ConfigureController
  File "/usr/local/lib/python3.7/site-packages/jdcloud_cli/controllers/configure_controller.py", line 68
    print 'access-key is required.'
                                  ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('access-key is required.')?

**Comment by oulinbao** [comment]
CLI v1.0.0 support python v3, please try.
