### ISSUE TITLE
jdc for python3 does not work

### ISSUE THREAD

**Issue by lidaobing** [jdcloud-api/jdcloud-cli#33]
```
$ jdc
Traceback (most recent call last):
  File "/usr/local/bin/jdc", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/jdcloud_cli/jdc.py", line 98, in main
    app.run()
  File "/usr/local/lib/python3.7/site-packages/cement/core/foundation.py", line 905, in run
    return_val = self.controller._dispatch()
  File "/usr/local/lib/python3.7/site-packages/cement/ext/ext_argparse.py", line 935, in _dispatch
    (contr.__class__.__name__, func_name))      # pragma: nocover
cement.core.exc.FrameworkError: Controller function does not exist BaseController.default()
```

**Comment by oulinbao** [comment]
this bug is fixed in cli v1.0.3.
